services:
  - type: worker
    name: telegram-trading-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python pocket-option.py"
    envVars:
      - key: 7954820177:AAGyODLYEdPqGY6_y0Cgh0QE5Ujjkb8V_P4
        sync: false
     


